### ISSUE TITLE
I wonder will the datasets and codes be available? And the website on paper is also 502.

### ISSUE THREAD

**Issue by PolarisRisingWar** [yyy-Apple/KIDReview#1]
As the caption. I found this paper interesting but I sadly found this GitHub project and the official website (http://nlpeer.reviews/) haven't available yet. So I wonder when can I got these resources?

**Comment by yyy-Apple** [comment]
Thanks for your interest!

* For the GitHub project: We will organize and release the code in the next few days.
* For the Demo: We stopped the current service because it requires much expense to host the server. We will re-start it once the computational resource is sufficient (not sure when).

**Comment by yyy-Apple** [comment]
Hi, we have updated the code and dataset.
